// Builds lib/geo-data.ts: KSA outline, neighbour outlines and the Mercator parameters.
import { geoMercator, geoPath } from "d3-geo";
import { feature } from "topojson-client";
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
const require = createRequire(import.meta.url);
const w50 = require("world-atlas/countries-50m.json");
const w110 = require("world-atlas/countries-110m.json");
const W = 1000, H = 780, EXT = [33, 15.5, 57, 33.5];
const box = { type: "Polygon", coordinates: [[[EXT[0], EXT[1]], [EXT[0], EXT[3]], [EXT[2], EXT[3]], [EXT[2], EXT[1]], [EXT[0], EXT[1]]]] };
const proj = geoMercator().fitExtent([[8, 8], [W - 8, H - 8]], box);
const path = geoPath(proj).digits(1);
const f50 = feature(w50, w50.objects.countries).features;
const f110 = feature(w110, w110.objects.countries).features;
const ksa = f50.find((f) => String(f.id) === "682");
const neighbours = f110.filter((f) => String(f.id) !== "682").map((f) => path(f)).filter(Boolean).join(" ");
const out = `// Generated by scripts/build-geo.mjs. Do not edit.
export const VIEW = { w: ${W}, h: ${H} } as const;
export const MERC = { k: ${proj.scale()}, tx: ${proj.translate()[0]}, ty: ${proj.translate()[1]} } as const;
export const KSA_PATH = ${JSON.stringify(path(ksa))};
export const NEIGHBOUR_PATH = ${JSON.stringify(neighbours)};
`;
writeFileSync(new URL("./src/geo-data.ts", import.meta.url), out);
console.log("geo-data bytes", out.length, "k", proj.scale(), proj.translate());
